services:

  app:
    image: sigaetutorial:latest
    container_name: sigae-app
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_HOST=${DATABASE_HOST:-postgres}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-sigae_db}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-sigae}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE:-true}
      - DATABASE_LOGGING=${DATABASE_LOGGING:-true}
      - DATABASE_SSL=${DATABASE_SSL:-false}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1h}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your_jwt_refresh_secret}
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sigae-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: sigae-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-sigae_db}
      POSTGRES_USER: ${DATABASE_USERNAME:-sigae}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sigae-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-sigae} -d ${DATABASE_NAME:-sigae_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  sigae-network:
    driver: bridge